name = "timoeta"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"

# Map your Worker to the custom domain.
# This requires the domain to be added to Cloudflare and DNS proxied.
routes = [
  { pattern = "eta.hkjc.uk/*", zone_name = "hkjc.uk" }
]
